config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about', as: 'pages_about'
  get 'contact', to: 'pages#contact', as: 'pages_contact'

  resources :blogs
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolio_items = Portfolio.all
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'New portfilio was created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The portfoli was successfully updated.' }
      else
        format.html { render new }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      @portfolio_item.destroy
      format.html { redirect_to portfolios_path }
    end
  end

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :portfolio_item_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :portfolio_item_subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :portfolio_item_body %>
  </div>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image, id: :portfolio_item_main_image %>
  </div>

  <div class="field">
    <%= form.label :thumb_image %>
    <%= form.text_area :thumb_image, id: :portfolio_item_thumb_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create", new_portfolio_path %>

<% @portfolio_items.each do |portfolio| %>
<h3><%= link_to portfolio.title, portfolio_show_path(portfolio) %></h3>
<p><%= portfolio.subtitle %></p>
<p><%= portfolio.body %></p>
<p><%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %></p>
<br />
<%= link_to "Edit", edit_portfolio_path(portfolio) %>
<%= link_to "Delete", portfolio, method: :delete, data: { confirm: "Are you sure to delete this item?"} %>
<hr />
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h2>
  <strong>Title:</strong>
  <%= @portfolio_item.title %>
</h2>
<h3>
  <%= @portfolio_item.subtitle %>
</h3>
<p>
  <%= @portfolio_item.body %>
</p>